apiVersion: v1
kind: Service
metadata:
  name: blogy-api-service
spec:
  selector:
    app: blogy-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort

